name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dart
      uses: dart-lang/setup-dart@v1
    - name: Install libserialport
      run: sudo apt install -y libserialport0
    - name: Install tty0tty
      run: |
        git clone https://github.com/lcgamboa/tty0tty.git
        sudo apt install -y linux-headers-`uname -r`
        cd tty0tty/module
        make -j $(nproc)
        sudo make install
        cd -
    - name: Run tty0tty
      run: tty0tty &
    - name: Fixup Permissions
      run: sudo chmod a+rw /dev/tnt*
    - name: Get Dependencies
      run: dart pub get
    - name: Run Tests
      run: dart pub run test
      env:
        # Ubuntu doesn't install libserialport.so
        LIBSERIALPORT_PATH: libserialport.so.0
